#pragma once
enum TAG_GAME_
{
	TAG_GAME_SP_PLAYER_DIE = 0,
	TAG_GAME_SP_PLAYER_FULL = 10,

	TAG_GAME_SP_PLAYER_MISSILE,
	TAG_GAME_SP_ITEM,

	TAG_GAME_SP_ENEMY_DIY = 90,
	TAG_GAME_SP_ENEMY_FULL = 100,

	TAG_GAME_LB_SCORE = 1000,
	TAG_GAME_LB_SCORE_HIGHSCORE,
	TAG_GAME_LB_PLAYER_LIFE,
	TAG_GAME_MN_GAME_OVER
};

enum SEQUENCE_RENDER_
{
	SEQUENCE_RENDER_MAP,
	SEQUENCE_RENDER_PLAYER_MISSILE,
	SEQUENCE_RENDER_PLAYER,
	SEQUENCE_RENDER_ITEM,
	SEQUENCE_RENDER_ENEMY,

	SEQUENCE_RENDER_CLOUD,

	SEQUENCE_RENDER_SCORE
};

#define PLYAER_MISSILE_DAMAGE 2
#define ENEMY_MISSILE_DAMAGE 1